// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

function createStubClient() {
  return new Proxy(
    {},
    {
      get() {
        throw new Error(
          'Supabase client not initialized. Please define VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'
        );
      }
    }
  ) as ReturnType<typeof createClient<Database>>;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let client: ReturnType<typeof createClient<Database>>;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    'Missing Supabase credentials. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'
  );
  client = createStubClient();
} else {
  client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = client;
